### ISSUE TITLE
See if by removing the Query model we can remove wagtail from INSTALLED_APPS

### ISSUE THREAD

**Issue by specialunderwear** [django-oscar/django-oscar-elasticsearch#19]

**Comment by sasha0** [comment]
Btw do we really need to rewrite original Wagtail's management command? Seems like the original one already has all necessary params and etc:

https://github.com/django-oscar/django-oscar-elasticsearch/blob/21beb191dc717bbc01a3c8335b574b3ebdaa6727/oscar_elasticsearch/search/management/commands/update_oscar_index.py#L8-L29

**Comment by specialunderwear** [comment]
There are 2 reasons for that, the first is that in older versions of wagtail, the chunk_size paramenter was broken because it specified the wring type. The second one is that wagtail's default chunk size is very likely to cause errors because it will send too much data to elasticsearch in 1 go.
